version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: sol_indexer_db
    environment:
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: indexer_pwd
      POSTGRES_DB: indexer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: sol_indexer_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
