[package]
name = "redis-adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
async-trait = "0.1.89"
redis = { version = "0.32.5", features = ["tokio-comp"] }
futures = "0.3.31"
