[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
diesel = { version = "2.2.12", features = ["postgres"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
