[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
bs58 = "0.5.1"
serde = { version = "1.0.219", features = ["derive"] }
yellowstone-grpc-client = "9.0.0"
yellowstone-grpc-proto = "9.0.0"

